<?php 

/**
 * Wise Chat admin localization settings tab class.
 *
 * @author Kainex <contact@kaine.pl>
 */
class WiseChatLocalizationTab extends WiseChatAbstractTab {

	public function getFields() {
		return array(
			array('_section', 'Localization Settings'),
			array(
				'hint_message', 'Hint Message', 'stringFieldCallback', 'string',
				'A hint message displayed in the message input field'
			),
			array(
				'user_name_prefix', 'User Name Prefix', 'stringFieldCallback', 'string',
				'Anonymous user\'s name prefix'
			),
			array(
				'message_submit_button_caption', 'Submit Button Caption', 'stringFieldCallback', 'string',
				'Caption for message submit button'
			),
			array('window_title', 'Window Title', 'stringFieldCallback', 'string', 'Title of the messages window'),
			array('users_list_title', 'Users List Title', 'stringFieldCallback', 'string', 'Title of the users lists (displayed only in Facebook-like mode)'),
			array('users_list_search_hint', 'Users List Search Hint', 'stringFieldCallback', 'string'),
			array('message_save', '"Save" message', 'stringFieldCallback', 'string'),
			array('message_reset', '"Reset" message', 'stringFieldCallback', 'string'),
			array('message_name', '"Name" message', 'stringFieldCallback', 'string'),
			array('message_customize', '"Customize" message', 'stringFieldCallback', 'string'),
			array('message_sending', '"Sending" message', 'stringFieldCallback', 'string'),
			array('message_mute_sounds', '"Mute sounds" message', 'stringFieldCallback', 'string'),
			array('message_enable_notifications', '"Enable E-mail Notifications" message', 'stringFieldCallback', 'string'),
			array('message_text_color', '"Text color" message', 'stringFieldCallback', 'string'),
			array('message_total_users', '"Total users" message', 'stringFieldCallback', 'string'),
			array('message_sec_ago', '"sec. ago" message', 'stringFieldCallback', 'string'),
			array('message_min_ago', '"min. ago" message', 'stringFieldCallback', 'string'),
			array('message_yesterday', '"yesterday" message', 'stringFieldCallback', 'string'),
            array('message_insert_emoticon', '"Insert an emoticon" message', 'stringFieldCallback', 'string'),
            array('message_insert_into_message', '"Insert into message" message', 'stringFieldCallback', 'string'),
			array('message_picture_upload_hint', '"Upload a picture" message', 'stringFieldCallback', 'string'),
			array('message_attach_file_hint', '"Attach a file" message', 'stringFieldCallback', 'string'),
			array('message_channel_password_authorization_hint', 'Channel Authorization Hint', 'stringFieldCallback', 'string'),
			array('message_login', '"Log in" message', 'stringFieldCallback', 'string'),
			array('message_enter_user_name', '"Enter your username" message', 'stringFieldCallback', 'string'),
			array('message_input_title', 'Message input hint', 'stringFieldCallback', 'string'),
			array('message_has_left_the_channel', 'has left the channel', 'stringFieldCallback', 'string'),
			array('message_has_joined_the_channel', 'has joined the channel', 'stringFieldCallback', 'string'),
			array('message_users_list_empty', '"No users in the channel" message', 'stringFieldCallback', 'string'),
			array('message_login_using', '"Login using" message', 'stringFieldCallback', 'string'),
			array('message_login_anonymously', '"Log in anonymously" message', 'stringFieldCallback', 'string'),
			array('message_approve_message', '"Approve the message" message', 'stringFieldCallback', 'string'),
			array('message_delete_message', '"Delete the message" message', 'stringFieldCallback', 'string'),
			array('message_edit_message', '"Edit the message" message', 'stringFieldCallback', 'string'),
			array('message_reply_to_message', '"Reply to" message', 'stringFieldCallback', 'string'),
			array('message_ban_this_user', '"Ban this user" message', 'stringFieldCallback', 'string'),
			array('message_kick_this_user', '"Kick this user" message', 'stringFieldCallback', 'string'),
			array('message_report_spam', '"Report spam" message', 'stringFieldCallback', 'string'),

			array('message_yes', '"Yes" message', 'stringFieldCallback', 'string'),
			array('message_no', '"No" message', 'stringFieldCallback', 'string'),
			array('message_ok', '"OK" message', 'stringFieldCallback', 'string'),
			array('message_ignore_user', '"Ignore this user" message', 'stringFieldCallback', 'string'),
			array('message_information', '"Information" message', 'stringFieldCallback', 'string'),
			array('message_invitation', '"Invitation" message', 'stringFieldCallback', 'string'),
			array('message_maximize', '"Maximize" message', 'stringFieldCallback', 'string'),
			array('message_minimize', '"Minimize" message', 'stringFieldCallback', 'string'),
			array('message_close', '"Close" message', 'stringFieldCallback', 'string'),
			array('message_send_a_message', '"Send a message" message', 'stringFieldCallback', 'string'),
			array('message_facebook_user', '"Facebook user" message', 'stringFieldCallback', 'string'),
			array('message_twitter_user', '"Twitter user" message', 'stringFieldCallback', 'string'),
			array('message_google_user', '"Google user" message', 'stringFieldCallback', 'string'),
			array('message_anonymous_user', '"Anonymous user" message', 'stringFieldCallback', 'string'),

			array('message_no_recent_chats', '"No recent chats" message', 'stringFieldCallback', 'string'),
			array('message_user_not_found_in_chat', '"The user is not in the chat" message', 'stringFieldCallback', 'string'),

			array('message_info_1', 'Information message #1', 'stringFieldCallback', 'string', 'Message: "This user is ignored by you. Would you like to stop ignoring this user?"'),
			array('message_info_2', 'Information message #2', 'stringFieldCallback', 'string', 'Message: "XYZ invites you to the private chat. Do you accept it?"'),
			array('message_info_3', 'Information message #3', 'stringFieldCallback', 'string', 'Message: "The message has been posted, but first it must be approved by the administrator."'),

			array('message_error_1', 'Message error #1', 'stringFieldCallback', 'string', 'Message: "Only letters, number, spaces, hyphens and underscores are allowed"'),
			array('message_error_2', 'Message error #2', 'stringFieldCallback', 'string', 'Message: "This name is already occupied"'),
			array('message_error_3', 'Message error #3', 'stringFieldCallback', 'string', 'Message: "You were banned from posting messages"'),
			array('message_error_4', 'Message error #4 (HTML)', 'stringFieldCallback', 'rawString', 'Message: "Only logged in users are allowed to enter the chat"'),
			array('message_error_5', 'Message error #5 (HTML)', 'stringFieldCallback', 'rawString', 'Message: "The chat is closed now"'),
			array('message_error_6', 'Message error #6 (HTML)', 'stringFieldCallback', 'rawString', 'Message: "The chat is full now. Try again later."'),
			array('message_error_7', 'Message error #7', 'stringFieldCallback', 'string', 'Message: "Unsupported type of file."'),
			array('message_error_8', 'Message error #8', 'stringFieldCallback', 'string', 'Message: "The size of the file exceeds allowed limit."'),
			array('message_error_9', 'Message error #9', 'stringFieldCallback', 'string', 'Message: "Invalid password."'),
			array('message_error_10', 'Message error #10 (HTML)', 'stringFieldCallback', 'rawString', 'Message: "You cannot enter the chat due to the limit of channels you can participate simultaneously."'),
			array('message_error_11', 'Message error #11 (HTML)', 'stringFieldCallback', 'string', 'Message: "You are not allowed to enter the chat."'),
			array('message_error_12', 'Message error #12 (HTML)', 'stringFieldCallback', 'string', 'Message: "You are blocked from using the chat."'),
			array('message_error_13', 'Message error #13', 'stringFieldCallback', 'string', 'Message: "The length of the message exceeds allowed limit."'),
			array('message_error_14', 'Message error #14 (HTML)', 'stringFieldCallback', 'rawString', 'Message: "You are not allowed to send private messages to this user."'),

			array('message_text_1', 'Message text #1', 'stringFieldCallback', 'string', 'Message: "Are you sure you want to report the message as spam?"'),

			array('_section', 'BuddyPress Integration Localization'),
			array('message_bp_manage_tab_name', 'Manage Chat Tab', 'stringFieldCallback', 'string'),
			array('message_bp_manage_enable_chat', 'Label #1', 'stringFieldCallback', 'string', 'Label: "Enable Chat"'),
			array('message_bp_manage_tab_position', 'Label #2', 'stringFieldCallback', 'string', 'Label: "Tab Position"'),
			array('message_bp_manage_tab_label', 'Label #3', 'stringFieldCallback', 'string', 'Label: "Tab Label"'),
			array('message_bp_manage_permissions', 'Label #4', 'stringFieldCallback', 'string', 'Label: "Tab Permissions"'),
			array('message_bp_manage_permissions_mods_delete', 'Label #5', 'stringFieldCallback', 'string', 'Label: "Allow mods to delete messages"'),
			array('message_bp_manage_permissions_mods_ban', 'Label #6', 'stringFieldCallback', 'string', 'Label: "Allow mods to ban users"'),
			array('message_bp_manage_permissions_mods_edit', 'Label #7', 'stringFieldCallback', 'string', 'Label: "Allow mods to edit messages"'),
			array('message_bp_manage_permissions_admins_delete', 'Label #8', 'stringFieldCallback', 'string', 'Label: "Allow admins to delete messages"'),
			array('message_bp_manage_permissions_admins_ban', 'Label #9', 'stringFieldCallback', 'string', 'Label: "Allow admins to ban users"'),
			array('message_bp_manage_permissions_admins_edit', 'Label #10', 'stringFieldCallback', 'string', 'Label: "Allow admins to edit messages"'),
			array('message_bp_manage_notice', 'Label #11', 'stringFieldCallback', 'string', 'Label: "Notice:"'),
			array('message_bp_manage_notice_text', 'Label #12', 'stringFieldCallback', 'string', 'Label: "These permissions will work only with enabled admin actions in Wise Chat Pro settings"'),
			array('message_bp_manage_shortcode', 'Label #13', 'stringFieldCallback', 'string', 'Label: "Wise Chat Pro detailed parameters (shortcode syntax required)"'),
			array('message_bp_manage_shortcode_example', 'Label #14', 'stringFieldCallback', 'string', 'Label: "Example:"'),
			array('message_bp_chat_message', 'Label #15', 'stringFieldCallback', 'string', 'Label: "Chat Message"'),
		);
	}
	
	public function getDefaultValues() {
		return array(
			'hint_message' => 'Enter message here',
			'user_name_prefix' => 'Anonymous',
			'message_submit_button_caption' => 'Send',
			'message_save' => 'Save',
			'message_reset' => 'Reset',
			'message_name' => 'Name',
			'message_customize' => 'Customize',
			'message_sending' => 'Sending ...',
			'message_error_1' => 'Only letters, number, spaces, hyphens and underscores are allowed',
			'message_error_2' => 'This name is already occupied',
			'message_error_3' => 'You were banned from posting messages',
			'message_error_4' => 'Only logged in users are allowed to enter the chat',
			'message_error_5' => 'The chat is closed now',
			'message_error_6' => 'The chat is full now. Try again later.',
			'message_error_7' => 'Unsupported type of file.',
			'message_error_8' => 'The size of the file exceeds allowed limit.',
			'message_error_9' => 'Invalid password.',
			'message_error_10' => 'You cannot enter the chat due to the limit of channels you can participate simultaneously.',
			'message_error_11' => 'You are not allowed to enter the chat.',
			'message_error_12' => 'You are blocked from using the chat.',
			'message_error_13' => 'The length of the message exceeds allowed limit.',
			'message_error_14' => 'You are not allowed to send private messages to this user.',
			'message_text_1' => 'Are you sure you want to report the message as spam?',
			'window_title' => 'Wise Chat Pro',
			'users_list_title' => 'Users List',
			'users_list_search_hint' => 'Search ...',
			'message_enable_notifications' => 'Enable E-mail Notifications',
			'message_mute_sounds' => 'Mute sounds',
			'message_text_color' => 'Text color',
			'message_total_users' => 'Total users',
			'message_sec_ago' => 'sec. ago',
			'message_min_ago' => 'min. ago',
			'message_yesterday' => 'yesterday',
            'message_insert_emoticon' => 'Insert an emoticon',
            'message_insert_into_message' => 'Insert into message',
			'message_picture_upload_hint' => 'Upload a picture',
			'message_attach_file_hint' => 'Attach a file',
			'message_channel_password_authorization_hint' => 'This channel is protected. Enter your password:',
			'message_login' => 'Log in',
			'message_login_using' => 'Log in using',
			'message_login_anonymously' => 'Log in anonymously',
			'message_approve_message' => 'Approve the message',
			'message_delete_message' => 'Delete the message',
			'message_edit_message' => 'Edit the message',
			'message_reply_to_message' => 'Reply to',
			'message_ban_this_user' => 'Ban this user',
			'message_kick_this_user' => 'Kick this user',
			'message_report_spam' => 'Report spam',
			'message_enter_user_name' => 'Enter your username',
			'message_input_title' => 'Use Shift+ENTER in order to move to the next line',
			'message_has_left_the_channel' => 'has left the channel',
			'message_has_joined_the_channel' => 'has joined the channel',
			'message_users_list_empty' => 'No users in the channel',
			'message_yes' => 'Yes',
			'message_no' => 'No',
			'message_ok' => 'OK',
			'message_ignore_user' => 'Ignore this user',
			'message_information' => 'Information',
			'message_invitation' => 'Invitation',
			'message_maximize' => 'Maximize',
			'message_minimize' => 'Minimize',
			'message_close' => 'Close',
			'message_send_a_message' => 'Send a message',
			'message_facebook_user' => 'Facebook user',
			'message_twitter_user' => 'Twitter user',
			'message_google_user' => 'Google user',
			'message_anonymous_user' => 'Anonymous user',
			'message_no_recent_chats' => 'No recent chats',
			'message_user_not_found_in_chat' => 'The user is not in the chat',

			'message_info_1' => 'This user is ignored by you. Would you like to stop ignoring this user?',
			'message_info_2' => 'invites you to the private chat. Do you accept it?',
			'message_info_3' => 'The message has been posted, but first it must be approved by the administrator.',

			'message_bp_manage_tab_name' => 'Chat',
			'message_bp_manage_enable_chat' => 'Enable Chat',
			'message_bp_manage_tab_position' => 'Tab Position',
			'message_bp_manage_tab_label' => 'Tab Label',
			'message_bp_manage_permissions' => 'Tab Permissions',
			'message_bp_manage_permissions_mods_delete' => 'Allow mods to delete messages',
			'message_bp_manage_permissions_mods_ban' => 'Allow mods to ban users',
			'message_bp_manage_permissions_mods_edit' => 'Allow mods to edit messages',
			'message_bp_manage_permissions_admins_delete' => 'Allow admins to delete messages',
			'message_bp_manage_permissions_admins_ban' => 'Allow admins to ban users',
			'message_bp_manage_permissions_admins_edit' => 'Allow admins to edit messages',
			'message_bp_manage_notice' => 'Notice:',
			'message_bp_manage_notice_text' => 'These permissions will work only with enabled admin actions in Wise Chat Pro settings',
			'message_bp_manage_shortcode' => 'Wise Chat Pro detailed parameters (shortcode syntax required)',
			'message_bp_manage_shortcode_example' => 'Example:',
			'message_bp_chat_message' => 'Chat Message',
		);
	}
}